version: '3.0'

scanning-settings:
  max-depth: 6
  exclude: [
    .nox/*
  ]
  include-files: []
  system:
    targets: []


report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []
      vulnerabilities:
        70612:
          reason: Not using the impacted function
          expires: '2024-12-31'


fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - high
        - medium
        - critical
      exploitability:
        - high
        - medium
        - critical

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch
